--- 
pool: 
  vmImage: ubuntu-latest
steps: 
  - 
    displayName: "Cache Maven local repo"
    inputs: 
      key: $(Build.SourcesDirectory)/pom.xml
      path: $(MAVEN_CACHE_FOLDER)
    task: CacheBeta@0
  - 
    displayName: "Download secure file"
    inputs: 
      secureFile: settings.xml
    name: settings
    task: DownloadSecureFile@1
  - 
    inputs: 
      script: |
          New-Item -Type Directory -Force "${HOME}/.m2"
          Copy-Item -Force "${settingxml.secureFilePath}"  "${HOME}/.m2/settings.xml"
      targettype: inline
    task: PowerShell@2
  - 
    inputs: 
      effectivePomSkip: true
      goals: "clean install package deploy $(MAVEN_OPTS) -DmuleDeploy -Dserver=${server} -Denvironment=${environment} -Dworkers=${workers} -DworkerType=${workerType}  -Dapp.runtime={app.runtime}  -Dapp.name=${app.name}"
      javaHomeOption: JDKVersion
      jdkArchitectureOption: x64
      jdkVersionOption: "1.8"
      mavenAuthenticationFeed: true
      mavenOptions: "-Xmx3072m"
      mavenPomFile: pom.xml
      mavenVersionOption: Default
      publishJUnitResults: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
    task: Maven@3
trigger: 
  batch: true
  branches: 
    include: 
      - development
  paths: 
    exclude: 
      - azure-pipelines.yml
variables: 
  - 
    group: Build-Variable-Group
  - 
    name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - 
    name: MAVEN_OPTS
    value: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"
